[program:hwoj-discordbot]
command=/home/oj/HWOJ/discordbot/.venv/bin/python app.py
directory=/home/oj/HWOJ/discordbot
stopsignal=QUIT
stdout_logfile=/tmp/hwoj-discordbot.stdout.log
stderr_logfile=/tmp/hwoj-discordbot.stderr.log
